# Refer to golangci-lint's example config file for more options and information:
# https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml

run:
  concurrency: 4
  timeout: 5m
  modules-download-mode: readonly

linters:
  fast: false
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosec
    - govet
    - misspell
    - staticcheck
    - unused

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
